"""conversation e query_log.conversation_id/turn_index (ADR-0016)

Revision ID: 6cf5cfaf87e7
Revises: d7f3a9c1b204
Create Date: 2026-07-11 19:57:08.253636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6cf5cfaf87e7'
down_revision: Union[str, None] = 'd7f3a9c1b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('squad_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('query_log', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.add_column('query_log', sa.Column('turn_index', sa.Integer(), nullable=True))
    op.create_index('ix_querylog_conversation_turn', 'query_log', ['conversation_id', 'turn_index'], unique=False)
    op.create_foreign_key(
        'fk_querylog_conversation_id', 'query_log', 'conversation', ['conversation_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_querylog_conversation_id', 'query_log', type_='foreignkey')
    op.drop_index('ix_querylog_conversation_turn', table_name='query_log')
    op.drop_column('query_log', 'turn_index')
    op.drop_column('query_log', 'conversation_id')
    op.drop_table('conversation')
    # ### end Alembic commands ###
