"""initial schema (org, taxonomy, document, links, chunk, ingestion_job)

Revision ID: 78d0b3b785b3
Revises: 
Create Date: 2026-07-09 13:18:04.771987
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '78d0b3b785b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('squad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('delivery_process',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'name', name='uq_process_squad_name')
    )
    op.create_index(op.f('ix_delivery_process_squad_id'), 'delivery_process', ['squad_id'], unique=False)
    op.create_table('subcategory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_subcat_category_name')
    )
    op.create_index(op.f('ix_subcategory_category_id'), 'subcategory', ['category_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_process_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('doc_type', sa.String(length=120), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('classification_source', sa.String(length=10), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification_source IS NULL OR classification_source IN ('llm','user')", name='ck_document_classification_source'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_process_id'], ['delivery_process.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_category_id'), 'document', ['category_id'], unique=False)
    op.create_index(op.f('ix_document_delivery_process_id'), 'document', ['delivery_process_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('milvus_vector_id', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunk_doc_ordinal')
    )
    op.create_index('ix_chunk_document', 'chunk', ['document_id'], unique=False)
    op.create_table('document_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('target_document_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("link_type IN ('esclarece','complementa','precede','substitui')", name='ck_link_type'),
    sa.CheckConstraint('source_document_id <> target_document_id', name='ck_link_no_self'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'target_document_id', 'link_type', name='uq_link')
    )
    op.create_index('ix_link_source', 'document_link', ['source_document_id'], unique=False)
    op.create_index('ix_link_target', 'document_link', ['target_document_id'], unique=False)
    op.create_table('ingestion_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending','processing','indexed','failed')", name='ck_job_state'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_job_document_id'), 'ingestion_job', ['document_id'], unique=False)
    op.create_index('ix_job_claim', 'ingestion_job', ['state', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_claim', table_name='ingestion_job')
    op.drop_index(op.f('ix_ingestion_job_document_id'), table_name='ingestion_job')
    op.drop_table('ingestion_job')
    op.drop_index('ix_link_target', table_name='document_link')
    op.drop_index('ix_link_source', table_name='document_link')
    op.drop_table('document_link')
    op.drop_index('ix_chunk_document', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_document_delivery_process_id'), table_name='document')
    op.drop_index(op.f('ix_document_category_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_subcategory_category_id'), table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index(op.f('ix_delivery_process_squad_id'), table_name='delivery_process')
    op.drop_table('delivery_process')
    op.drop_table('squad')
    op.drop_table('category')
    # ### end Alembic commands ###
