"""query_log e system_log (ADR-0010/0011)

Revision ID: cc34b9227367
Revises: 78d0b3b785b3
Create Date: 2026-07-09 15:31:18.253014
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cc34b9227367'
down_revision: Union[str, None] = '78d0b3b785b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('insufficient_context', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('chat_model', sa.String(length=200), nullable=True),
    sa.Column('chunk_size_words', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap_words', sa.Integer(), nullable=True),
    sa.Column('retrieval_min_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR rating IN (-1, 1)', name='ck_querylog_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_querylog_created', 'query_log', ['created_at'], unique=False)
    op.create_table('system_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("level IN ('INFO','WARN','ERROR')", name='ck_syslog_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_syslog_component', 'system_log', ['component'], unique=False)
    op.create_index('ix_syslog_ts', 'system_log', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_syslog_ts', table_name='system_log')
    op.drop_index('ix_syslog_component', table_name='system_log')
    op.drop_table('system_log')
    op.drop_index('ix_querylog_created', table_name='query_log')
    op.drop_table('query_log')
    # ### end Alembic commands ###
